export const productsSeed = [
  {
    id: 1,
    name: "Awesome App",
    slug: "awesome-app",
    tagline: "Make life easier",
    description: "This app simplifies everything.",
    websiteUrl: "https://awesomeapp.com",
    tags: { category: "productivity", platform: "web" },
    voteCount: 10,
    status: "approved",
    submittedBy: "Ovi",
    userId: "user-1",
    organaizationId: "org-1",
  },
  {
    id: 2,
    name: "Cool Tool",
    slug: "cool-tool",
    tagline: "Tool for cool people",
    description: "A very cool tool for developers.",
    websiteUrl: "https://cooltool.com",
    tags: { category: "developer", platform: "web" },
    voteCount: 5,
    status: "pending",
    submittedBy: "Ovi",
    userId: "user-2",
    organaizationId: "org-2",
  },
  {
    id: 3,
    name: "Next Product",
    slug: "next-product",
    tagline: "Next-level product",
    description: "Advanced product for pro users.",
    websiteUrl: "https://nextproduct.com",
    tags: { category: "tech", platform: "mobile" },
    voteCount: 15,
    status: "approved",
    submittedBy: "Ovi",
    userId: "user-3",
    organaizationId: "org-1",
  },
];
